[gsm.version.ril-impl]: [Qualcomm RIL 1.0]
[init.svc.adbd]: [running]
[init.svc.android.thermal-hal]: [running]
[init.svc.apexd]: [stopped]
[init.svc.apexd-bootstrap]: [stopped]
[init.svc.apexd-snapshotde]: [stopped]
[init.svc.audioserver]: [running]
[init.svc.bootanim]: [stopped]
[init.svc.boringssl_self_test32]: [stopped]
[init.svc.boringssl_self_test32_vendor]: [stopped]
[init.svc.boringssl_self_test64]: [stopped]
[init.svc.boringssl_self_test64_vendor]: [stopped]
[init.svc.boringssl_self_test_apex32]: [stopped]
[init.svc.boringssl_self_test_apex64]: [stopped]
[init.svc.bpfloader]: [stopped]
[init.svc.cameraserver]: [running]
[init.svc.cnss-daemon]: [stopped]
[init.svc.credstore]: [running]
[init.svc.derive_classpath]: [stopped]
[init.svc.derive_sdk]: [stopped]
[init.svc.display-color-hal-1-0]: [running]
[init.svc.dmapp]: [running]
[init.svc.dpmQmiMgr]: [running]
[init.svc.dpmd]: [stopped]
[init.svc.drm]: [running]
[init.svc.eid-1-0]: [running]
[init.svc.feature_enabler_client]: [running]
[init.svc.freezerd]: [running]
[init.svc.gatekeeper-1-0]: [running]
[init.svc.gatekeeperd]: [running]
[init.svc.gnss_service]: [running]
[init.svc.gpu]: [running]
[init.svc.health-hal-2-1]: [running]
[init.svc.heapprofd]: [stopped]
[init.svc.hidl_memory]: [running]
[init.svc.hwservicemanager]: [running]
[init.svc.idmap2d]: [stopped]
[init.svc.incidentd]: [running]
[init.svc.installd]: [running]
[init.svc.iop-hal-2-0]: [running]
[init.svc.iorapd]: [stopped]
[init.svc.irsc_util]: [stopped]
[init.svc.kernel-boot]: [stopped]
[init.svc.kernel-post-boot]: [stopped]
[init.svc.keystore2]: [running]
[init.svc.lmkd]: [running]
[init.svc.loc_launcher]: [running]
[init.svc.logd]: [running]
[init.svc.logd-auditctl]: [stopped]
[init.svc.logd-reinit]: [stopped]
[init.svc.media]: [running]
[init.svc.media.swcodec]: [running]
[init.svc.mediadrm]: [running]
[init.svc.mediaextractor]: [running]
[init.svc.mediametrics]: [running]
[init.svc.mlid]: [running]
[init.svc.netd]: [stopped]
[init.svc.neuralnetworks_hal_service_shim_qti]: [running]
[init.svc.nfc_hal_service]: [running]
[init.svc.nqnfcinfo]: [stopped]
[init.svc.nubia.user_de.post]: [stopped]
[init.svc.nubia_dc_bright_ser]: [running]
[init.svc.odsign]: [stopped]
[init.svc.perf-hal-2-3]: [running]
[init.svc.poweropt-service]: [running]
[init.svc.qccsyshal@1.1-service]: [running]
[init.svc.qcom-c_core-sh]: [stopped]
[init.svc.qcom-c_main-sh]: [stopped]
[init.svc.qcom-post-boot]: [stopped]
[init.svc.qcom-sh]: [stopped]
[init.svc.qcomsysd]: [running]
[init.svc.qfp-daemon]: [running]
[init.svc.qseecom-service]: [running]
[init.svc.qspmhal]: [running]
[init.svc.qteeconnector-hal-1-0]: [running]
[init.svc.qti-media]: [stopped]
[init.svc.qti-testscripts]: [stopped]
[init.svc.qti_display_boot]: [stopped]
[init.svc.qvrd_vndr]: [running]
[init.svc.sec_chip_service]: [stopped]
[init.svc.secureprocessor-1-0]: [running]
[init.svc.sensorscal-hal-1-0]: [running]
[init.svc.servicemanager]: [running]
[init.svc.soter-1-0]: [running]
[init.svc.ssgqmigd]: [running]
[init.svc.statsd]: [running]
[init.svc.stc_oem]: [stopped]
[init.svc.storaged]: [running]
[init.svc.surfaceflinger]: [stopped]
[init.svc.sxrauxd]: [running]
[init.svc.sxrd]: [running]
[init.svc.system_suspend]: [running]
[init.svc.tcmd]: [running]
[init.svc.thermal-engine]: [running]
[init.svc.time_daemon]: [running]
[init.svc.tombstoned]: [running]
[init.svc.traced]: [running]
[init.svc.traced_perf]: [stopped]
[init.svc.traced_probes]: [running]
[init.svc.tui_comm-1-0]: [running]
[init.svc.ueventd]: [running]
[init.svc.update_engine]: [running]
[init.svc.update_verifier_nonencrypted]: [stopped]
[init.svc.usbd]: [stopped]
[init.svc.vendor-qti-media-c2-hal-1-0]: [running]
[init.svc.vendor-qti-media-c2audio-hal-1-0]: [running]
[init.svc.vendor-sensor-sh]: [stopped]
[init.svc.vendor.adsprpcd]: [running]
[init.svc.vendor.agm-1-0]: [running]
[init.svc.vendor.atfwd]: [running]
[init.svc.vendor.atrace-hal-1-0]: [running]
[init.svc.vendor.audio-hal]: [running]
[init.svc.vendor.audioadsprpcd_audiopd]: [running]
[init.svc.vendor.bluetooth-1-0-qti]: [running]
[init.svc.vendor.boot-hal-1-2]: [running]
[init.svc.vendor.camera-provider-2-7]: [running]
[init.svc.vendor.capabilityconfigstore]: [running]
[init.svc.vendor.cas-hal-1-2]: [running]
[init.svc.vendor.cdsprpcd]: [running]
[init.svc.vendor.cnd]: [running]
[init.svc.vendor.dataadpl]: [running]
[init.svc.vendor.dataqti]: [running]
[init.svc.vendor.diag-router]: [running]
[init.svc.vendor.dpmd]: [running]
[init.svc.vendor.drm-clearkey-hal-1-4]: [running]
[init.svc.vendor.drm-widevine-hal-1-4]: [running]
[init.svc.vendor.dspservice]: [running]
[init.svc.vendor.fps_hal]: [running]
[init.svc.vendor.identity]: [running]
[init.svc.vendor.ims_rtp_daemon]: [running]
[init.svc.vendor.imsdaemon]: [running]
[init.svc.vendor.ipacm]: [running]
[init.svc.vendor.ipacm-diag]: [running]
[init.svc.vendor.keymaster-4-1]: [running]
[init.svc.vendor.keymint-qti]: [running]
[init.svc.vendor.limits-hal]: [running]
[init.svc.vendor.lowi]: [running]
[init.svc.vendor.mdm_launcher]: [stopped]
[init.svc.vendor.media.omx]: [running]
[init.svc.vendor.modemManager]: [running]
[init.svc.vendor.modprobe]: [stopped]
[init.svc.vendor.msm_irqbalance]: [running]
[init.svc.vendor.mstatdaemon]: [running]
[init.svc.vendor.mutualex]: [stopped]
[init.svc.vendor.netmgrd]: [running]
[init.svc.vendor.nubia_hal_server]: [running]
[init.svc.vendor.pd_mapper]: [running]
[init.svc.vendor.per_mgr]: [running]
[init.svc.vendor.per_proxy]: [running]
[init.svc.vendor.perfservice]: [running]
[init.svc.vendor.port-bridge]: [running]
[init.svc.vendor.power]: [running]
[init.svc.vendor.qconfig]: [running]
[init.svc.vendor.qcrild]: [running]
[init.svc.vendor.qcrild2]: [running]
[init.svc.vendor.qesdk-mgr]: [running]
[init.svc.vendor.qmipriod]: [running]
[init.svc.vendor.qrtr-ns]: [running]
[init.svc.vendor.qseecomd]: [running]
[init.svc.vendor.qspmsvc]: [running]
[init.svc.vendor.qti.hardware.display.allocator]: [running]
[init.svc.vendor.qti.hardware.display.composer]: [running]
[init.svc.vendor.qti.hardware.display.demura]: [running]
[init.svc.vendor.qti.hardware.memtrack]: [running]
[init.svc.vendor.qti.light]: [running]
[init.svc.vendor.qti.vibrator]: [running]
[init.svc.vendor.qvirtmgr]: [running]
[init.svc.vendor.rmt_storage]: [running]
[init.svc.vendor.sensors]: [running]
[init.svc.vendor.sensors-hal-2-1-multihal]: [running]
[init.svc.vendor.sensors.qesdk]: [running]
[init.svc.vendor.sensors.qti]: [running]
[init.svc.vendor.servicetracker-1-2]: [running]
[init.svc.vendor.shsusrd]: [running]
[init.svc.vendor.ssgtzd]: [running]
[init.svc.vendor.ssr_setup]: [stopped]
[init.svc.vendor.tftp_server]: [running]
[init.svc.vendor.trustedui-1-0]: [running]
[init.svc.vendor.usb-hal-1-2]: [running]
[init.svc.vendor.usbgadget-hal-1-1]: [running]
[init.svc.vendor.vppservice]: [running]
[init.svc.vendor.wifi_hal_legacy]: [running]
[init.svc.vndservicemanager]: [running]
[init.svc.vold]: [running]
[init.svc.wfdhdcphalservice]: [running]
[init.svc.wfdvndservice]: [running]
[init.svc.wificond]: [stopped]
[init.svc.wifidisplayhalservice]: [running]
[init.svc.woodpeckerd]: [running]
[init.svc.wpa_supplicant]: [stopped]
[init.svc.zygote]: [running]
[init.svc.zygote_secondary]: [stopped]
[openwrt.phase2.module.done]: [1]
[openwrt.phase2.module.health]: [done]
[openwrt.phase2.module.openwrt]: [done]
[openwrt.phase2.module.pid]: [1108]
[openwrt.phase2.module.service]: [done]
[openwrt.phase2.module.service_result]: [net_applied_ok]
[openwrt.phase2.module.stage]: [postfs]
[openwrt.phase2.net.reason]: [ok]
[openwrt.phase2.net.state]: [applied]
[openwrt.phase2.net.table]: [rmnet_data2]
[openwrt.phase2.net.wan]: [rmnet_data2]
[openwrt.phase3.android.cnss]: [stopped]
[openwrt.phase3.android.netd]: [stopped]
[openwrt.phase3.android.wificond]: [stopped]
[openwrt.phase4.android.surfaceflinger]: [stopped]
[openwrt.phase4.android.zygote_primary]: [suspended_zygote64]
[openwrt.phase4.android.zygote_secondary]: [stopped]
[persist.radio.multisim.config]: [dsds]
[persist.vendor.data.mode]: [concurrent]
[persist.vendor.data.offload_ko_load]: [1]
[persist.vendor.data.perf_ko_load]: [1]
[persist.vendor.data.qmipriod_load]: [1]
[persist.vendor.data.shs_ko_load]: [1]
[persist.vendor.data.shsusr_load]: [1]
[persist.vendor.dpm.feature]: [0]
[persist.vendor.dpm.vndr.feature]: [11]
[persist.vendor.dpm.vndr.halservice.enable]: [1]
[persist.vendor.dpm.vndr.idletimer.mode]: [default]
[persist.vendor.dpm.vndr.tcm]: [2]
[ro.baseband]: [msm]
